- lib/server-lib.js
This is a new PR replacing https://github.com/ripple/ripple-rest/pull/253.  I changed the order so server was checked before checking remote._stand_alone then checking if server._lastLedgerClose was less then 30 seconds.  Below is my original PR comment.
When running rippled in standalone mode you have to manual advance the ledger, so unless you manually advance the ledger (30 seconds) before every api call you well get a network error. This isn't very useful to someone using ripple-rest to develop software using ripple-rest when in standalone mode. If someone is connecting to a standalone server I think it can be assumed that they know they will not have an up to date ledger and will have to manual advance the ledger to access any transactions in the open ledger.
I propose that we check …
> Check for rippled in standalone mode before returning false on lastLedgerClose check

- api/orders.js
- lib/utils.js
- test/fixtures/orders.js
- test/orders-test.js
- test/unit/utils-test.js
> [BUG] Orders: Correct mishandling XRP amounts and use 'counterparty' (RLJS-172)(RLJS-174)

- api/balances.js
Hex currencies were returning an error:
`// GET https://api.ripple.com/v1/accounts/rQE5Z3FgVnRMbVfS6xiVQFgB4J3X162FVD/balances?currency=0000000000000000000000000000000000000000`
```
{
"success": false,
"error_type": "invalid_request",
"error": "restINVALID_PARAMETER",
"message": "Parameter is not a valid currency: currency"
}
```
> [BUG] Balances: Allow hex currencies (RLJS-168)

- api/payments.js
- api/transactions.js
- schemas/RippleAddress.json
From the (wiki)[https://wiki.ripple.com/Accounts]
> In ripple-lib, use `UInt160.is_valid(x)`
```
> var validator = require('./lib/schema-validator.js');
> validator.isValid('rMwjYedjc7qqtKYVLiAccJSmCwih4LnE21', 'RippleAddress')
true
> var UInt160 = require('ripple-lib').UInt160
> UInt160.is_valid('rMwjYedjc7qqtKYVLiAccJSmCwih4LnE21')
false
```
> [BUG] Correctly validate RippleAddress and remove schema validator (RLJS-169)

- api/transactions.js
- lib/submit_transaction_hooks.js
- test/_payments-test.js
- test/fixtures/orders.js
- test/fixtures/settings.js
- test/fixtures/trustlines.js
- test/orders-test.js
- test/payments-test.js
- test/settings-test.js
- test/trustlines-test.js
With recent refactoring and an updated of ripple-lib, some transaction submissions started waiting for the transaction to be finalized instead of replying immediately with a status url. The only time we should wait for a transaction to be finalized before returning is when the `validated` flag is set to true, otherwise a status url should be returned. This PR fixes the recent regression
> [FIX] transaction submission regression

- api/orders.js
- test/fixtures/orders.js
Making [account orders api](https://ripple.com/build/ripple-rest/#get-account-orders)  consistent with [order objects](https://ripple.com/build/ripple-rest/#order-objects)
> [BUG] Orders: Make order objects consistent with order submission

- api/payments.js
- lib/tx-to-rest-converter.js
- test/fixtures/payments.js
- test/payments-test.js
- test/unit/fixtures/tx-converter.js
- Adds similar metadata to the `payment` object when requesting more
than one payment (`GET /v1/accounts/:address/payments`)
> [TASK] Payment History: Make response objects consistent (RLJS-160)

- README.md
- api/lib/tx-to-rest-converter.js
- test/fixtures/payments.js
- test/unit/fixtures/tx-converter.js
> [FEATURE] Payments: Add perspective account balance changes (RLJS-235)

- README.md
- api/lib/rest-to-tx-converter.js
- api/lib/tx-to-rest-converter.js
- api/lib/utils.js
- api/orders.js
- api/payments.js
- test/_payments-test.js
- test/fixtures/payments.js
- test/orders-test.js
- test/paths-test.js
- test/payments-test.js
- test/unit/fixtures/rest-converter.js
- test/unit/fixtures/tx-converter.js
- test/unit/rest-converter-test.js
- test/unit/tx-converter-test.js
- test/unit/utils-test.js
- This completes the conversion of all APIs in REST from using `issuer`
to `counterparty`
> [TASK] Payments: Use `counterparty` in place of `issuer`

- api/lib/logger.js
- server/express_app.js
- server/logger.js
- Use ELF Format for production express logs
See: http://www.w3.org/TR/WD-logfile
```
#Version: 1.0
#Date: 2015-02-20 01:08:16
#Software: 1.4.0
#Fields: c-ip date time cs-method cs-uri cs(Version) sc-status time-taken cs(User-Agent)
127.0.0.1 2015-02-20 01:08:18 GET /v1 1.1 304 4.612 Mozilla/5.0+(Macintosh;+Intel+Mac+OS+X+10_10_2)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/40.0.2214.111+Safari/537.36
```
> [FEATURE] Production logs in ELF format (RLJS-239)

- api/lib/notification_parser.js
- api/notifications.js
- test/fixtures/notifications.js
- test/notifications-test.js
- When requesting transactions in binary format, rippled does not
provide `date`
- To determinstically sort transactions in the same ledger, sort based
on `Sequence`
> [FIX] Notifications: Sort transactions on Sequence (RLJS-253)

- api/lib/utils.js
- api/notifications.js
- test/unit/utils-test.js
(RLJS-253)
- Previous fix was incorrectly sorting on Sequence, but that can only
sort transactions submitted by the same account
> [FIX] Notifications: Sort transcations on `meta.TransactionIndex`

- api/transactions.js
From `Remote` in ripple-lib:
`DEPRECATED: First argument to request constructor should be an object
containing request properties`
> [TASK] Fix ripple-lib deprecation warnings (RLJS-266)

- api/lib/rest-to-tx-converter.js
- test/unit/fixtures/rest-converter.js
- A SendMax value is calculated using source_slippage, but that is an
optional parameter.
- Typical client error:
```json
{
"success": false,
"error_type": "transaction",
"error": "plus() not a number: undefined"
}
```
> [FIX] `source_slippage` should default to zero

- README.md
- api/lib/rest-to-tx-converter.js
- api/lib/tx-to-rest-converter.js
- api/lib/utils.js
- api/payments.js
- test/_payments-test.js
- test/fixtures/payments.js
- test/orders-test.js
- test/paths-test.js
- test/payments-test.js
- test/unit/fixtures/rest-converter.js
- test/unit/fixtures/tx-converter.js
- test/unit/rest-converter-test.js
- test/unit/tx-converter-test.js
- test/unit/utils-test.js
This reverts commit 013efaa3c0c4fab34faf1ba0fb90d4d765aff399.
Includes a few changes to keep existing endpoints consistent with using
counterparty.
Conflicts:
README.md
api/lib/rest-to-tx-converter.js
api/lib/tx-to-rest-converter.js
api/lib/utils.js
api/orders.js
api/payments.js
test/_payments-test.js
> Revert "[TASK] Payments: Use `counterparty` in place of `issuer`"

- api/payments.js
- api/transactions.js
- test/_payments-test.js
- test/fixtures/payments.js
- test/payments-test.js
- Previously, payments were in two states: 'validate' or 'failed', and
'validated' status was determined incorrectly by checking the
transaction result
> [FIX] Payment state is pending until validated (RLJS-318)

- api/lib/rest-to-tx-converter.js
- test/fixtures/addresses.js
- test/unit/fixtures/rest-converter.js
- test/unit/rest-converter-test.js
- SendMax should not be set when the source and destination currencies
are the same and the issuers are "any that the source is able to use
and the destination is able to receive"
e.g.,
```javascript
source_amount: {
value: '0.0003272934271954',
currency: 'GWD',
issuer: ''
},
destination_amount: {
value: '0.0003272934271954',
currency: 'GWD',
issuer: 'r4p4gZaWSq8Cs1d8mn1jaGqVU1HUns1ek3'
}
```
- SendMax documentation:
https://ripple.com/build/transactions/#special-issuer-values-for-sendmax-and-amount
> [FIX] Correctly determine when to set SendMax (RLJS-272)

- api/notifications.js
- api/transactions.js
- server/routes.js
- getTransaction was not handling exceptions thrown by the validation
calls
- Example:
```
2015-04-13T22:54:51.183Z - error: uncaughtException: Parameter missing:
paymentIdentifier
{ date: 'Mon Apr 13 2015 22:54:51 GMT+0000 (UTC)',
```
> [FIX] Removing GET /notifications, handle exceptions in getTransaction

- api/lib/utils.js
- api/payments.js
- api/transactions.js
- server/routes.js
- test/unit/utils-test.js
Fix bug in earliest_first query parameter for Payment History API
> Fix payment history API `earliest_first` parameter and compare transactions on ledger order

- api/lib/rest-to-tx-converter.js
- test/unit/fixtures/rest-converter.js
- test/unit/rest-converter-test.js
- rippled 0.28 removes temredundant_send_max, in
https://github.com/ripple/rippled/commit/c522ffa6db2648f1d8a987843e7feabf1a0b7de8/
> Update SendMax logic to match rippled 0.28 (RLJS-336)

- npm-shrinkwrap.json
- package.json
Why?
- Consistently set a `resolved` field and reduce diff churn
- Local correctness for edge cases not handled by npm
https://github.com/uber/npm-shrinkwrap#motivation
Setup:
```
$ npm install
```
Or, make it available globally
```
$ npm install -g npm-shrinkwrap
```
Anytime dependencies are changed
```
$ ./node_modules/.bin/npm-shrinkwrap
$ ./node_modules/.bin/npm-shrinkwrap diff master HEAD
$ ./node_modules/.bin/npm-shrinkwrap diff HEAD npm-shrinkwrap.json --short
```
See: https://github.com/uber/npm-shrinkwrap
> Use npm-shrinkwrap
